FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# SuportU
This is document for SuportU 's REST API. All responses from and to the API will be in JSON format.

#General Request Response
Almost APIs requires a request with application/json content type (except API for upload file, image).

#Authentication
API use JWT to authenticate user. Exactly we used JWT Bearer Authentication.
Almost APIs requires authentication on header with Authorization tag and value formatted:

Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRw319.sSaOosOuPWvTYVL

#Error
We must catch common errors in all API to ensure our application works properly.

        {
            "code":"DB_ERROR",
            "message":"Cannot create new user!"
        }

|         HTTP CODE         |       Error code        |  Error message               |
|---------------------------|-------------------------|------------------------------|
|           401             |     unauthorized        |    Authen fail               |

## Group QuestionsCollection
Polls is a simple API allowing consumers to view polls and vote in them.
### GetUserInfo [GET /user/{id}]
Get user infomation.

+ Parameters
    + id - variable that is required
    
+ Response 200 (application/json)

        {
            "id": 1,
            "name": "Bui Duc Long",
            "email":"duclongbuivn@gmail.com"
        }
        
### Login [POST /login]
User login

+ Request (application/json)

        {
            "email": "duclongbuivn@gmail.com",
            "password": "123456"
        }

+ Response 201 (application/json)

        {
            "id": 1,
            "name": "Bui Duc Long",
            "email":"duclongbuivn@gmail.com"
        }